import Head from "next/head"
import Banner from "../views/Banner"
import Follow from "../views/Follow"
import Navbar from "../views/Navbar"
import Work from "../views/Work"
import Footer from "../views/Footer"
import Trending from "../views/Trending"
import HowItWorks from "../views/HowItWorks"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Finestra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logo.svg" />
      </Head>

      <main>
        <Navbar />
        <Banner />
        <Trending />
        <HowItWorks />
        <Work />
        <Follow />
        <Footer />
      </main>
    </div>
  )
}
